name: Pulsar CI

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 0.35.1
          - 1.0.0
        experimental:
          - false
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal_version }}-alpine

    steps:
      - uses: actions/checkout@v1
      - name: Format
        run: crystal tool format --check

  build:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 0.35.1
          - 1.0.0
        experimental:
          - false
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal_version }}-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Install shards
        run: shards install
      - name: Cache Crystal
        uses: actions/cache@v1
        with:
          path: ~/.cache/crystal
          key: ${{ runner.os }}-crystal
      - name: Run tests
        run: crystal spec
